In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("raw_data.xlsx")
df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Price,Total_Sales,Payment_Mode,Order_Status
0,ORD0001,2024-11-17,CUST456,PROD019,2,2400,4800,Card,Delivered
1,ORD0002,2024-11-24,CUST382,PROD015,2,55000,110000,UPI,Delivered
2,ORD0003,2024-02-26,CUST003,PROD017,1,1500,1500,Card,Delivered
3,ORD0004,2024-02-01,CUST359,PROD003,1,25000,25000,COD,Delivered
4,ORD0005,2024-03-04,CUST090,PROD005,2,1500,3000,UPI,Delivered

In [3]:
file = pd.ExcelFile("raw_data.xlsx")
print(file.sheet_names)

['Table_O', 'Orders', 'Table_C', 'Customers', 'Table_P', 'Products']

In [4]:
customers = pd.read_excel("raw_data.xlsx", sheet_name="Customers")
orders = pd.read_excel("raw_data.xlsx", sheet_name="Orders")
products = pd.read_excel("raw_data.xlsx", sheet_name="Products")

In [5]:
orders.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Price,Total_Sales,Payment_Mode,Order_Status
0,ORD0001,2024-03-11,CUST199,PROD013,1,700,700,UPI,Processing
1,ORD0002,2024-12-12,CUST243,PROD013,4,700,2800,COD,Delivered
2,ORD0003,2024-10-02,CUST029,PROD006,2,2000,4000,Card,Returned
3,ORD0004,2024-06-15,CUST010,PROD030,2,2400,4800,UPI,Delivered
4,ORD0005,2024-07-07,CUST402,PROD025,2,55000,110000,COD,Processing

In [6]:
customers.head()

  Customer_ID Customer_Name       City
0     CUST001         Priya  Hyderabad
1     CUST002          Ravi     Mumbai
2     CUST003          Ravi    Chennai
3     CUST004         Pooja  Bangalore
4     CUST005          Ravi  Hyderabad

In [7]:
products.head()

  Product_ID Product_Name     Category  Price
0    PROD001      Laptop   Electronics  55000
1    PROD002       Mobile  Electronics  20000
2    PROD003      Tablet   Electronics  25000
3    PROD004      Laptop   Electronics  55000
4    PROD005  Headphones   Electronics   1500

In [8]:
customers.info()
orders.info()
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    500 non-null    object
 1   Customer_Name  500 non-null    object
 2   City           500 non-null    object
dtypes: object(3)
memory usage: 11.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      1000 non-null   object
 1   Order_Date    1000 non-null   datetime64[ns]
 2   Customer_ID   1000 non-null   object
 3   Product_ID    1000 non-null   object
 4   Quantity      1000 non-null   int64
 5   Price         1000 non-null   int64
 6   Total_Sales   1000 non-null   int64
 7   Payment_Mode  1000 non-null   object
 8   Order_Status  1000 non-null   object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 70.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    30 non-null     object
 1   Product_Name  30 non-null     object
 2   Category      30 non-null     object
 3   Price         30 non-null     int64
dtypes: int64(1), object(3)
memory usage: 1.1+ KB

In [9]:
orders.isnull().sum()

Order_ID        0
Order_Date      0
Customer_ID     0
Product_ID      0
Quantity        0
Price           0
Total_Sales     0
Payment_Mode    0
Order_Status    0
dtype: int64

In [10]:
orders = orders.drop_duplicates()

In [11]:
orders.duplicated().sum()

np.int64(0)

In [12]:
orders = orders.dropna()

In [13]:
orders["Order_Date"] = pd.to_datetime(orders["Order_Date"])

In [14]:
orders["Order_Status"].unique()

array(['Processing', 'Delivered', 'Returned', 'Shipped', 'Cancelled'],
      dtype=object)

In [15]:
orders["Payment_Mode"].unique()

array(['UPI', 'COD', 'Card'], dtype=object)

In [16]:
orders["Total_Sales"] = orders["Quantity"] * orders["Price"]

In [17]:
orders.describe()

                       Order_Date    Quantity         Price    Total_Sales
count                        1000  1000.00000   1000.000000    1000.000000
mean   2024-06-28 02:06:43.200000     2.94700  17994.500000   52876.400000
min           2024-01-01 00:00:00     1.00000    400.000000     400.000000
25%           2024-03-26 18:00:00     2.00000   2000.000000    4500.000000
50%           2024-06-29 00:00:00     3.00000  20000.000000   20000.000000
75%           2024-09-26 00:00:00     4.00000  25000.000000   90000.000000
max           2024-12-30 00:00:00     5.00000  55000.000000  275000.000000
std                           NaN     1.40505  19452.634391   67939.426909

In [18]:
orders.to_csv("cleaned_orders.csv", index=False)

In [19]:
import os
os.getcwd()

'C:\\Users\\sakil\\OneDrive\\Desktop'

In [20]:
orders.to_csv("E:\\project\\data\\cleaned_orders.csv", index=False)

In [21]:
import os
os.getcwd()

'C:\\Users\\sakil\\OneDrive\\Desktop'

In [1]:
import pandas as pd

In [12]:
customers = pd.read_excel("E:/project/data/raw_data.xlsx", sheet_name="Customers")

In [13]:
print(customers.head())

  Customer_ID Customer_Name       City
0     CUST001         Priya  Hyderabad
1     CUST002          Ravi     Mumbai
2     CUST003          Ravi    Chennai
3     CUST004         Pooja  Bangalore
4     CUST005          Ravi  Hyderabad

In [14]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    500 non-null    object
 1   Customer_Name  500 non-null    object
 2   City           500 non-null    object
dtypes: object(3)
memory usage: 11.8+ KB

In [15]:
customers.isnull().sum()

Customer_ID      0
Customer_Name    0
City             0
dtype: int64

In [16]:
customers.duplicated().sum()

np.int64(0)

In [17]:
customers = customers.drop_duplicates()

In [19]:
customers["Customer_ID"].nunique()

500

In [20]:
customers["Customer_ID"].count()

np.int64(500)

In [21]:
customers["Customer_Name"] = customers["Customer_Name"].str.strip()
customers["City"] = customers["City"].str.strip()

In [22]:
customers["Customer_Name"] = customers["Customer_Name"].str.title()
customers["City"] = customers["City"].str.title()

In [23]:
customers["City"].unique()

array(['Hyderabad', 'Mumbai', 'Chennai', 'Bangalore', 'Delhi', 'Kolkata',
       'Pune', 'Ahmedabad'], dtype=object)

In [24]:
customers.to_csv("E:/project/data/cleaned_customers.csv", index=False)

In [25]:
products = pd.read_excel("E:/project/data/raw_data.xlsx", sheet_name="Products")

In [26]:
products.head()

  Product_ID Product_Name     Category  Price
0    PROD001      Laptop   Electronics  55000
1    PROD002       Mobile  Electronics  20000
2    PROD003      Tablet   Electronics  25000
3    PROD004      Laptop   Electronics  55000
4    PROD005  Headphones   Electronics   1500

In [27]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    30 non-null     object
 1   Product_Name  30 non-null     object
 2   Category      30 non-null     object
 3   Price         30 non-null     int64
dtypes: int64(1), object(3)
memory usage: 1.1+ KB

In [28]:
products.isnull().sum()

Product_ID      0
Product_Name    0
Category        0
Price           0
dtype: int64

In [29]:
products = products.dropna()

In [30]:
products.duplicated().sum()

np.int64(0)

In [31]:
products = products.drop_duplicates()

In [32]:
products["Product_ID"].nunique()
products["Product_ID"].count()

np.int64(30)

In [33]:
products["Product_Name"] = products["Product_Name"].str.strip()
products["Category"] = products["Category"].str.strip()

In [34]:
products["Product_Name"] = products["Product_Name"].str.title()
products["Category"] = products["Category"].str.title()

In [35]:
products["Category"].unique()

array(['Electronics', 'Clothing'], dtype=object)

In [36]:
products["Category"].unique()

array(['Electronics', 'Clothing'], dtype=object)

In [37]:
products = pd.read_excel("E:/project/data/raw_data.xlsx", sheet_name="Products")

In [38]:
products["Category"].unique()

array(['Electronics', 'Footwear', 'Clothing', 'Accessories'], dtype=object)

In [39]:
products.describe()

             Price
count     30.00000
mean   17680.00000
std    19693.08298
min      400.00000
25%     2000.00000
50%    11200.00000
75%    25000.00000
max    55000.00000

In [40]:
products.to_csv("E:/project/data/cleaned_products.csv", index=False)

In [42]:
customers = pd.read_excel("raw_data.xlsx", sheet_name="Customers")
orders = pd.read_excel("raw_data.xlsx", sheet_name="Orders")
products = pd.read_excel("raw_data.xlsx", sheet_name="Products")

In [43]:
orders["Customer_ID"].isin(customers["Customer_ID"]).all()

np.True_

In [44]:
orders["Product_ID"].isin(products["Product_ID"]).all()

np.True_

In [45]:
orders[(orders["Price"] <= 0) | (orders["Quantity"] <= 0)]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Product_ID, Quantity, Price, Total_Sales, Payment_Mode, Order_Status]
Index: []